name: nightlybuild-tabsidebar-for-windows for x86

on:
  workflow_dispatch:
  schedule:
    # 毎日日本時間の午前8時に実施する。
    - cron: '0 23 * * *'

jobs:

  build:
    runs-on: windows-latest

    steps:
      - name: Checkout actions/checkout@v2
        uses: actions/checkout@v2
        
      - name: vimver.bat
        id: vimver
        shell: cmd
        run: |
          vimver.bat >> $GITHUB_OUTPUT
          
      - name: Update tabsidebar repository
        shell: cmd
        run: |
          git config --global user.email "naru123456789@gmail.com"
          git config --global user.name "rbtnn"
          git clone https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/rbtnn/vim.git
          cd vim
          git remote add upstream https://github.com/vim/vim.git
          git fetch upstream
          git merge upstream/master
          git push -u origin tabsidebar
          git checkout tabsidebar_disabled
          git merge tabsidebar
          git push -u origin tabsidebar_disabled
          git checkout tabsidebar
                    
      - name: Checkout ilammy/msvc-dev-cmd@v1
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86

      - name: Build Vim
        shell: cmd
        run: |
          cd vim\src
          nmake /nologo /f Make_mvc.mak GUI=yes USE_WIN32MAK=no COLOR_EMOJI=yes OLE=yes DYNAMIC_IME=yes IME=yes GIME=yes DEBUG=no ICONV=yes
          nmake /nologo /f Make_mvc.mak GUI=no  USE_WIN32MAK=no COLOR_EMOJI=yes OLE=yes DYNAMIC_IME=yes IME=yes GIME=yes DEBUG=no ICONV=yes

      - name: create-zip.bat
        shell: cmd
        run: |
          cd vim
          ..\create-zip.bat

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        with:
          tag_name: ${{ steps.vimver.outputs.vimver }}
          release_name: Release-${{ steps.vimver.outputs.vimver }}
          draft: false
          prerelease: false

      - name: Upload nightlybuild-tabsidebar-for-windows.zip as Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./vim/nightlybuild-tabsidebar-for-windows.zip
          asset_name: nightlybuild-tabsidebar-for-windows.zip
          asset_content_type: application/zip
   
      - name: Update version.txt
        shell: cmd
        run: |
          echo "[DEBUG] ${{ steps.vimver.outputs.vimver }}"
          git config --global user.email "naru123456789@gmail.com"
          git config --global user.name "rbtnn"
          echo ${{ steps.vimver.outputs.vimver }} > version.txt
          git add version.txt
          git commit -m "Release-${{ steps.vimver.outputs.vimver }}"
          git push -u origin master       
